### ISSUE TITLE
With a M1 mac, pre-commit run fails: urllib.error.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by jcdrubay** [OCA/oca-addons-repo-template#119]
## Module
pre-commit / node version

## Describe the bug

`pre-commit run -a` raise the following error:

```
An unexpected error has occurred: CalledProcessError: command: ('/opt/homebrew/opt/python@3.9/bin/python3.9', '-mnodeenv', '--prebuilt', '--clean-src', '/Users/jc/.cache/pre-commit/repoxfnstb3k/node_env-14.13.0', '-n', '14.13.0')
return code: 1
expected return code: 0
stdout: (none)
stderr:
     * Install prebuilt node (14.13.0) .
    Traceback (most recent call last):
      File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/opt/homebrew/lib/python3.9/site-packages/nodeenv.py", line 1494, in <module>
        main()
      File "/opt/homebrew/lib/python3.9/site-packages/nodeenv.py", line 1079, in main
        create_environment(env_dir, opt)
      File "/opt/homebrew/lib/python3.9/site-packages/nodeenv.py", line 956, in create_environment
        install_node(env_dir, src_dir, opt)
      File "/opt/homebrew/lib/python3.9/site-packages/nodeenv.py", line 721, in install_node
        install_node_wrapped(env_dir, src_dir, opt)
ADJ: When generating invoices ...
      File "/opt/homebrew/lib/python3.9/site-packages/nodeenv.py", line 743, in install_node_wrapped
        download_node_src(node_url, src_dir, opt)
      File "/opt/homebrew/lib/python3.9/site-packages/nodeenv.py", line 570, in download_node_src
        dl_contents = io.BytesIO(urlopen(node_url).read())
      File "/opt/homebrew/lib/python3.9/site-packages/nodeenv.py", line 606, in urlopen
        return urllib2.urlopen(req)
      File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
        return opener.open(url, data, timeout)
      File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
        response = meth(req, response)
      File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
        response = self.parent.error(
      File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
        return self._call_chain(*args)
      File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
        result = func(*args)
      File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 404: Not Found
```

## Suggested solution

Upgrading node fixes the issue:

```diff
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
index 58f8baf9..d78138ed 100644
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -16,7 +16,7 @@ exclude: |
   (LICENSE.*|COPYING.*)
 default_language_version:
   python: python3
-  node: "14.13.0"
+  node: "17.2.0"
 repos:
   - repo: local
     hooks:
```

**Comment by jcdrubay** [comment]
I hope there can be a follow up on this 🫤

**Comment by isserver1** [comment]
> I hope there can be a follow up on this 🫤

I think you need to open a PR. It more straightforward way to have it done faster

**Comment by jcdrubay** [comment]
Thanks for the tip @isserver1 but in which repo should I do this?

The precommit-config.yml file in this repo is very different from this one: https://github.com/OCA/web/blob/14.0/.pre-commit-config.yaml

Normally, it should be done in all OCA repos 😅 

I believe / hope that maintainers have efficient ways to populate all OCA repos with such changes.

**Comment by yajo** [comment]
Yes, this is the place. The template is at https://github.com/OCA/oca-addons-repo-template/blob/master/src/.pre-commit-config.yaml.jinja and you can PR that file.

Your case is a bit cumbersome, because if that nodejs version breaks the pinned nodejs dependencies, that's gonna be a problem. Mostly if none of the maintainers owns an M1.

**Comment by StefanRijnhart** [comment]
@jcdrubay did you create a PR for this, or find another solution/workaround? A team member of mine is running into this problem.

**Comment by jcdrubay** [comment]
I @StefanRijnhart Unfortunatly, I have no other solution than to upgrade the pre-commit config file manually as in the Suggested Solution I mention, and then the other way.

I did not create a PR as I foresee that it will be done in the wrong place if I try myself.
