### ISSUE TITLE
pre-commit: Black < 22 is incompatible with click 8.1.0

### ISSUE THREAD

**Issue by ap-wtioit** [OCA/oca-addons-repo-template#133]
## Module
.pre-commit-config.yaml

## Describe the bug
When running pre-commit in [web](https://github.com/OCA/web/blob/15.0/.pre-commit-config.yaml) we get the following exception:
```
black....................................................................Failed
- hook id: black
- exit code: 1
Traceback (most recent call last):
  File "/home/oca-precommit/.cache/pre-commit/repov0kwiinn/py_env-python3/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/home/oca-precommit/.cache/pre-commit/repov0kwiinn/py_env-python3/lib/python3.8/site-packages/black/__init__.py", line 6606, in patched_main
    patch_click()
  File "/home/oca-precommit/.cache/pre-commit/repov0kwiinn/py_env-python3/lib/python3.8/site-packages/black/__init__.py", line 6595, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/home/oca-precommit/.cache/pre-commit/repov0kwiinn/py_env-python3/lib/python3.8/site-packages/click/__init__.py)
```

## To Reproduce
**Affected versions**:
* black < 22
* click 8.1.0

1. run a fresh install of pre-commit with pre-commit config from [web](https://github.com/OCA/web/blob/15.0/.pre-commit-config.yaml)

**Expected behavior**
pre-commit should be runnable without exceptions in its dependencies if the code is ok

**Additional context**
see https://github.com/psf/black/issues/2964
as this problem most likely not only affects web, i opened the issue here to have the solution propagated to all oca addons repos

**Comment by pedrobaeza** [comment]
Do you have any hint how to fix it? Is click an implicit dependency not declared in the config https://github.com/OCA/web/blob/15.0/.pre-commit-config.yaml so we can't pin it?

**Comment by ap-wtioit** [comment]
i'm currently testing workarrounds, seems like 22.1.0 is still affected but 22.3.0 is not (for web 15.0)

**Comment by sbidoul** [comment]
The proposed fix (pinning click is good). That said, I'm inclined to upgrade black to 22.3, at least for 14.0 and 15.0 as the changes in formatting should be very minor.

**Comment by Tardo** [comment]
From what I have tried updating black should not make many (apparently none) formatting changes as @sbidoul comments.
