### ISSUE TITLE
Build broken: test (16, 3.10, ubuntu-22.04) "AttributeError: 'bytes' object has no attribute 'tell'"

### ISSUE THREAD

**Issue by simahawk** [OCA/oca-addons-repo-template#186]
https://github.com/OCA/oca-addons-repo-template/actions/runs/4043175714/jobs/6951788247
```
               | [INFO] Installing environment for https://github.com/pre-commit/mirrors-prettier.
              | [INFO] Once installed this environment will be reused.
              | [INFO] This may take a few minutes...
              | An unexpected error has occurred: CalledProcessError: command: ('/home/runner/.cache/pypoetry/virtualenvs/oca-addons-repo-template-k8g-9Ttz-py3.10/bin/python', '-mnodeenv', '--prebuilt', '--clean-src', '/home/runner/.cache/pre-commit/repoj6kwn2uz/node_env-16.17.0', '-n', '16.17.0')
              | return code: 1
              | expected return code: 0
              | stdout: (none)
              | stderr:
              |      * Install prebuilt node (16.17.0) .Incomplete read while readingfrom https://nodejs.org/download/release/v16.17.0/node-v16.17.0-linux-x64.tar.gz
              |     .
              |     Traceback (most recent call last):
              |       File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/runpy.py", line 196, in _run_module_as_main
              |         return _run_code(code, main_globals, None,
              |       File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/runpy.py", line 86, in _run_code
              |         exec(code, run_globals)
              |       File "/home/runner/.cache/pypoetry/virtualenvs/oca-addons-repo-template-k8g-9Ttz-py3.10/lib/python3.10/site-packages/nodeenv.py", line 1519, in <module>
              |         main()
              |       File "/home/runner/.cache/pypoetry/virtualenvs/oca-addons-repo-template-k8g-9Ttz-py3.10/lib/python3.10/site-packages/nodeenv.py", line 1104, in main
              |         create_environment(env_dir, args)
              |       File "/home/runner/.cache/pypoetry/virtualenvs/oca-addons-repo-template-k8g-9Ttz-py3.10/lib/python3.10/site-packages/nodeenv.py", line 980, in create_environment
              |         install_node(env_dir, src_dir, args)
              |       File "/home/runner/.cache/pypoetry/virtualenvs/oca-addons-repo-template-k8g-9Ttz-py3.10/lib/python3.10/site-packages/nodeenv.py", line 739, in install_node
              |         install_node_wrapped(env_dir, src_dir, args)
              |       File "/home/runner/.cache/pypoetry/virtualenvs/oca-addons-repo-template-k8g-9Ttz-py3.10/lib/python3.10/site-packages/nodeenv.py", line 762, in install_node_wrapped
              |         download_node_src(node_url, src_dir, args)
              |       File "/home/runner/.cache/pypoetry/virtualenvs/oca-addons-repo-template-k8g-9Ttz-py3.10/lib/python3.10/site-packages/nodeenv.py", line 602, in download_node_src
              |         with ctx as archive:
              |       File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/contextlib.py", line 135, in __enter__
              |         return next(self.gen)
              |       File "/home/runner/.cache/pypoetry/virtualenvs/oca-addons-repo-template-k8g-9Ttz-py3.10/lib/python3.10/site-packages/nodeenv.py", line 573, in tarfile_open
              |         tf = tarfile.open(*args, **kwargs)
              |       File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/tarfile.py", line 1630, in open
              |         saved_pos = fileobj.tell()
              |     AttributeError: 'bytes' object has no attribute 'tell'
```
Noticed here too https://github.com/OCA/sale-reporting/actions/runs/4076516610/jobs/7024352420

**Comment by simahawk** [comment]
@pedrobaeza re-ran the one on the PR and it worked :man_shrugging: https://github.com/OCA/sale-reporting/actions/runs/4076516610/jobs/7035897120

I'm re-running the on here on the template... let's see https://github.com/OCA/oca-addons-repo-template/actions/runs/4043175714

**Comment by pedrobaeza** [comment]
Yes, I was about to say that.

**Comment by simahawk** [comment]
the error is gone on master too :partying_face:
