### ISSUE TITLE
15.0 Pre-commit fails

### ISSUE THREAD

**Issue by bosd** [OCA/oca-addons-repo-template#193]
## Module
The repo template for v 15.0. As used in purchase-workflow

## Describe the bug
Pre-commit fails on gh actions. Due to failing nodejs v14.18.0 installation for pre-commit. 

## To Reproduce
**Affected versions**: 15.0

1. Open a PR in a repo for version V15

**Expected behavior**
Pre-commit test working correctly

**Additional context**

```
An unexpected error has occurred: CalledProcessError: command: ('/opt/hostedtoolcache/Python/3.11.2/x64/bin/python', '-mnodeenv', '--prebuilt', '--clean-src', '/home/runner/.cache/pre-commit/repokgr7im5p/node_env-14.18.0', '-n', '14.18.0')
return code: 1
stdout: (none)
stderr:
    /opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/nodeenv.py:26: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.[13](https://github.com/OCA/purchase-workflow/actions/runs/4615875319/jobs/8160215978?pr=1833#step:7:14)
      import pipes
     * Install prebuilt node ([14](https://github.com/OCA/purchase-workflow/actions/runs/4615875319/jobs/8160215978?pr=1833#step:7:15).18.0) .Incomplete read while readingfrom https://nodejs.org/download/release/v14.18.0/node-v14.18.0-linux-x64.tar.gz
    .
    Traceback (most recent call last):
      File "<frozen runpy>", line 198, in _run_module_as_main
      File "<frozen runpy>", line 88, in _run_code
      File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/nodeenv.py", line [15](https://github.com/OCA/purchase-workflow/actions/runs/4615875319/jobs/8160215978?pr=1833#step:7:16)19, in <module>
        main()
      File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/nodeenv.py", line 1104, in main
        create_environment(env_dir, args)
      File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/nodeenv.py", line 980, in create_environment
        install_node(env_dir, src_dir, args)
      File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/nodeenv.py", line 739, in install_node
        install_node_wrapped(env_dir, src_dir, args)
      File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/nodeenv.py", line 762, in install_node_wrapped
        download_node_src(node_url, src_dir, args)
      File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/nodeenv.py", line 602, in download_node_src
        with ctx as archive:
      File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/contextlib.py", line 137, in __enter__
        return next(self.gen)
               ^^^^^^^^^^^^^^
      File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/nodeenv.py", line 573, in tarfile_open
        tf = tarfile.open(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/tarfile.py", line [16](https://github.com/OCA/purchase-workflow/actions/runs/4615875319/jobs/8160215978?pr=1833#step:7:17)[30](https://github.com/OCA/purchase-workflow/actions/runs/4615875319/jobs/8160215978?pr=1833#step:7:31), in open
        saved_pos = fileobj.tell()
                    ^^^^^^^^^^^^
    AttributeError: 'bytes' object has no attribute 'tell'
Check the log at /home/runner/.cache/pre-commit/pre-commit.log
Error: Process completed with exit code 3.
```
as discovered in: https://github.com/OCA/purchase-workflow/pull/1827

**Comment by bosd** [comment]
@yajo Another one for your list :grinning:

**Comment by yajo** [comment]
Haha thanks @bosd, added it. It's fun to keep it updated! 😄

**Comment by pedrobaeza** [comment]
This is a temporary glitch that happens from time to time. Just retry.
