### ISSUE TITLE
[13.0] Pre commit fails with "AttributeError: module 'collections' has no attribute 'MutableSet'"

### ISSUE THREAD

**Issue by LoisRForgeFlow** [OCA/oca-addons-repo-template#80]
See [this pipeline](https://github.com/OCA/manufacture/runs/3962457025) from https://github.com/OCA/manufacture/pull/665.

Error trace:

```
install pre-commit
/opt/hostedtoolcache/Python/3.10.0/x64/bin/pre-commit run --show-diff-on-failure --color=always --all-files
[INFO] Initializing environment for https://github.com/oca/maintainer-tools.
[INFO] Initializing environment for https://github.com/myint/autoflake.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-prettier.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-prettier:@prettier/plugin-xml@0.7.2,prettier@1.19.1.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-eslint.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-eslint:eslint@6.8.0.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/asottile/pyupgrade.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-isort.
[INFO] Initializing environment for https://github.com/acsone/setuptools-odoo.
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8.
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8:flake8-bugbear==19.8.0.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-pylint.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-pylint:pylint-odoo==3.5.0.
[INFO] Installing environment for https://github.com/oca/maintainer-tools.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/myint/autoflake.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-prettier.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-eslint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/asottile/pyupgrade.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/acsone/setuptools-odoo.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://gitlab.com/pycqa/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-pylint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
forbidden files......................................(no files to check)Skipped
Update pre-commit excluded addons........................................Passed
Fix the manifest website key.............................................Passed
autoflake................................................................Passed
black....................................................................Passed
prettier (with plugin-xml)...............................................Passed
eslint...............................................(no files to check)Skipped
- hook id: eslint
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Debug Statements (Python)................................................Passed
Fix python encoding pragma...............................................Passed
Check for case conflicts.................................................Passed
Check docstring is first.................................................Passed
Check that executables have shebangs.................(no files to check)Skipped
Check for merge conflicts................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Check Xml................................................................Passed
Mixed line ending........................................................Passed
pyupgrade................................................................Passed
isort except __init__.py.................................................Passed
Generate default setup.py for an addons directory........................Passed
flake8...................................................................Passed
pylint with optional checks..............................................Failed
- hook id: pylint
- duration: 0.61s
- exit code: 1

Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/pylint/lint/run.py", line 254, in __init__
    linter.load_default_plugins()
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 483, in load_default_plugins
    checkers.initialize(self)
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/pylint/checkers/__init__.py", line 64, in initialize
    register_plugins(linter, __path__[0])
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/pylint/utils/utils.py", line 245, in register_plugins
    module = modutils.load_module_from_file(
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/astroid/modutils.py", line 240, in load_module_from_file
    return load_module_from_modpath(modpath)
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/astroid/modutils.py", line 225, in load_module_from_modpath
    return load_module_from_name(".".join(parts))
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/astroid/modutils.py", line 210, in load_module_from_name
    return importlib.import_module(dotted_name)
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/pylint/checkers/imports.py", line 49, in <module>
    import isort
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/isort/__init__.py", line 25, in <module>
    from . import settings  # noqa: F401
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/isort/settings.py", line 34, in <module>
    from .pie_slice import itemsview, lru_cache, native_str
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/isort/pie_slice.py", line 362, in <module>
    class OrderedSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'
Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/pylint/lint/run.py", line 254, in __init__
    linter.load_default_plugins()
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 483, in load_default_plugins
    checkers.initialize(self)
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/pylint/checkers/__init__.py", line 64, in initialize
    register_plugins(linter, __path__[0])
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/pylint/utils/utils.py", line 245, in register_plugins
    module = modutils.load_module_from_file(
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/astroid/modutils.py", line 240, in load_module_from_file
    return load_module_from_modpath(modpath)
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/astroid/modutils.py", line 225, in load_module_from_modpath
    return load_module_from_name(".".join(parts))
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/astroid/modutils.py", line 210, in load_module_from_name
    return importlib.import_module(dotted_name)
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/pylint/checkers/imports.py", line 49, in <module>
    import isort
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/isort/__init__.py", line 25, in <module>
    from . import settings  # noqa: F401
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/isort/settings.py", line 34, in <module>
    from .pie_slice import itemsview, lru_cache, native_str
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/isort/pie_slice.py", line 362, in <module>
    class OrderedSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'

pylint with mandatory checks.............................................Failed
- hook id: pylint
- exit code: 1

Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/pylint/lint/run.py", line 254, in __init__
    linter.load_default_plugins()
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 483, in load_default_plugins
    checkers.initialize(self)
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/pylint/checkers/__init__.py", line 64, in initialize
    register_plugins(linter, __path__[0])
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/pylint/utils/utils.py", line 245, in register_plugins
    module = modutils.load_module_from_file(
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/astroid/modutils.py", line 240, in load_module_from_file
    return load_module_from_modpath(modpath)
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/astroid/modutils.py", line 225, in load_module_from_modpath
    return load_module_from_name(".".join(parts))
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/astroid/modutils.py", line 210, in load_module_from_name
    return importlib.import_module(dotted_name)
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/pylint/checkers/imports.py", line 49, in <module>
    import isort
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/isort/__init__.py", line 25, in <module>
    from . import settings  # noqa: F401
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/isort/settings.py", line 34, in <module>
    from .pie_slice import itemsview, lru_cache, native_str
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/isort/pie_slice.py", line 362, in <module>
    class OrderedSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'
Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/pylint/lint/run.py", line 254, in __init__
    linter.load_default_plugins()
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 483, in load_default_plugins
    checkers.initialize(self)
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/pylint/checkers/__init__.py", line 64, in initialize
    register_plugins(linter, __path__[0])
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/pylint/utils/utils.py", line 245, in register_plugins
    module = modutils.load_module_from_file(
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/astroid/modutils.py", line 240, in load_module_from_file
    return load_module_from_modpath(modpath)
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/astroid/modutils.py", line 225, in load_module_from_modpath
    return load_module_from_name(".".join(parts))
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/astroid/modutils.py", line 210, in load_module_from_name
    return importlib.import_module(dotted_name)
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/pylint/checkers/imports.py", line 49, in <module>
    import isort
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/isort/__init__.py", line 25, in <module>
    from . import settings  # noqa: F401
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/isort/settings.py", line 34, in <module>
    from .pie_slice import itemsview, lru_cache, native_str
  File "/home/runner/.cache/pre-commit/repo8exd_olr/py_env-python3/lib/python3.10/site-packages/isort/pie_slice.py", line 362, in <module>
    class OrderedSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'

Error: The process '/opt/hostedtoolcache/Python/3.10.0/x64/bin/pre-commit' failed with exit code 1
```

Any clue what the issue can be?

**Comment by sbidoul** [comment]
Moved to oca/oca-addons-repo-template. 

It looks like the pre-commit action now uses python 3.10, which triggers a bug in the old isort version used by pylint-odoo...
MutableSet is now in collections.abc. *Starting with Python 3.3, importing ABCs from collections was deprecated, and importing should be done from collections.abc. Being able to import from collections was marked for removal in 3.8, but has been delayed to 3.9. (See bpo-36952.)*

We should try pinning the python version used by pre-commit to 3.6 [here](https://github.com/OCA/oca-addons-repo-template/blob/5cea348797e800f8b5518001ecb1704fdcb774c4/src/.github/workflows/pre-commit.yml#L12).

**Comment by dreispt** [comment]
@sbidoul This does not solve the problem when running pre-commit locally.
IMO pre-commit config should be updated.

**Comment by sbidoul** [comment]
> @sbidoul This does not solve the problem when running pre-commit locally.
> IMO pre-commit config should be updated.

This issue is very old. Can you make sure you have updated the repo with the latest template and open another issue with details?

**Comment by pedrobaeza** [comment]
Try going `pre-commit install -f`

**Comment by dreispt** [comment]
@sbidoul Yes it is old, and gets more visible as more people get Python 3.10 in their workstations.
The problem is that pre-commit config is "frozen" for Odoo version <=13, and libraries used there are incompatible with Python 3.10.

@pedrobaeza Thanks for the suggestion, it didn't work.

Steps to reproduce: 

On Ubuntu 22.04, Python 3.10.6, 
- clone oca/manufacture:
- git checkout 13.0
- pre-commit install -f
- pre-commit run -a

You will end up with errors:
```
(...)
  File "/home/dreis/.cache/pre-commit/repo3ewi_r6p/py_env-python3/lib/python3.10/site-packages/pylint/checkers/imports.py", line 49, in <module>
    import isort
  File "/home/dreis/.cache/pre-commit/repo3ewi_r6p/py_env-python3/lib/python3.10/site-packages/isort/__init__.py", line 25, in <module>    from . import settings  # noqa: F401
  File "/home/dreis/.cache/pre-commit/repo3ewi_r6p/py_env-python3/lib/python3.10/site-packages/isort/settings.py", line 34, in <module>    from .pie_slice import itemsview, lru_cache, native_str
  File "/home/dreis/.cache/pre-commit/repo3ewi_r6p/py_env-python3/lib/python3.10/site-packages/isort/pie_slice.py", line 362, in <module>
    class OrderedSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'

```

The problem are the "frozen" configs here: https://github.com/OCA/oca-addons-repo-template/tree/master/version-specific

**Comment by pedrobaeza** [comment]
And updating the copier template? In OCA/l10n-spain, I don't have such problem in 13.0 because I updated.

**Comment by sbidoul** [comment]
Yes, the old configs now require specific python version (see for instance [here](https://github.com/OCA/oca-addons-repo-template/blob/master/version-specific/13.0/.pre-commit-config.yaml.jinja#L18) for 13, which requires python 3.8)
